name: Java CI with Maven and Spring Boot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Package with Maven
      run: mvn clean package -DskipTests

    - name: Run Tests
      run: mvn test

    - name: Build Spring Boot Executable Jar
      run: mvn spring-boot:repackage

    - name: Upload Spring Boot Jar Artifact
      uses: actions/upload-artifact@v4
      with:
        name: spring-boot-app
        path: target/*.jar
